// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2dOBVj3HdV0ag2TqjZFDDhHxytv6ob_k',
    appId: '1:835047690792:web:ba392b0b032bf93a52db1d',
    messagingSenderId: '835047690792',
    projectId: 'mysynclist',
    authDomain: 'mysynclist.firebaseapp.com',
    storageBucket: 'mysynclist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfLBUVnAlZ7Z2fKatf8bCs2G0OWSkg98',
    appId: '1:835047690792:android:c9a83717b79afd1d52db1d',
    messagingSenderId: '835047690792',
    projectId: 'mysynclist',
    storageBucket: 'mysynclist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSuyY0F-6_q7PNvfB2FcL9pSOwMqJZZs',
    appId: '1:835047690792:ios:9652604e7a497d4a52db1d',
    messagingSenderId: '835047690792',
    projectId: 'mysynclist',
    storageBucket: 'mysynclist.firebasestorage.app',
    iosBundleId: 'com.example.mysynclist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXSuyY0F-6_q7PNvfB2FcL9pSOwMqJZZs',
    appId: '1:835047690792:ios:9652604e7a497d4a52db1d',
    messagingSenderId: '835047690792',
    projectId: 'mysynclist',
    storageBucket: 'mysynclist.firebasestorage.app',
    iosBundleId: 'com.example.mysynclist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2dOBVj3HdV0ag2TqjZFDDhHxytv6ob_k',
    appId: '1:835047690792:web:9a6874ce09630dc452db1d',
    messagingSenderId: '835047690792',
    projectId: 'mysynclist',
    authDomain: 'mysynclist.firebaseapp.com',
    storageBucket: 'mysynclist.firebasestorage.app',
  );
}
